"""adding tables for AL

Revision ID: 00c4506074ad
Revises: 2026_03_20_drop_ranking_score
Create Date: 2026-03-26 18:56:56.593408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR
# revision identifiers, used by Alembic.
revision = '00c4506074ad'
down_revision = '2026_03_20_drop_ranking_score'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('al_model_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('checkpoint_path', sa.String(), nullable=False),
    sa.Column('label_config_path', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('is_base', sa.Integer(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'LOADING', 'ERROR', name='al_model_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_checkpoint_id'], ['al_model_checkpoints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'name', 'version', name='uq_al_checkpoint')
    )
    op.create_index(op.f('ix_al_model_checkpoints_dataset_id'), 'al_model_checkpoints', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_al_model_checkpoints_id'), 'al_model_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_al_model_checkpoints_parent_checkpoint_id'), 'al_model_checkpoints', ['parent_checkpoint_id'], unique=False)
    op.create_table('al_retrain_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('feedback_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='al_retrain_status_enum'), nullable=False),
    sa.Column('result_metrics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_checkpoint_id'], ['al_model_checkpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_al_retrain_jobs_dataset_id'), 'al_retrain_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_al_retrain_jobs_id'), 'al_retrain_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_al_retrain_jobs_model_checkpoint_id'), 'al_retrain_jobs', ['model_checkpoint_id'], unique=False)
    op.create_table('al_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('snippet_id', sa.Integer(), nullable=False),
    sa.Column('predicted_labels', sa.JSON(), nullable=False),
    sa.Column('predicted_probabilities', sa.JSON(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('diversity', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('embedding', VECTOR(dim=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_checkpoint_id'], ['al_model_checkpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_checkpoint_id', 'snippet_id', name='uq_al_prediction')
    )
    op.create_index(op.f('ix_al_predictions_id'), 'al_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_al_predictions_model_checkpoint_id'), 'al_predictions', ['model_checkpoint_id'], unique=False)
    op.create_index(op.f('ix_al_predictions_snippet_id'), 'al_predictions', ['snippet_id'], unique=False)
    op.create_table('al_snippet_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('snippet_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('GROUND_TRUTH', 'USER', name='al_annotation_source_enum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_checkpoint_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_checkpoint_id'], ['al_model_checkpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snippet_id', 'label', 'source', 'user_id', 'model_checkpoint_id', name='uq_al_snippet_label_source_user_ckpt')
    )
    op.create_index(op.f('ix_al_snippet_annotation_dataset_id'), 'al_snippet_annotation', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_al_snippet_annotation_label'), 'al_snippet_annotation', ['label'], unique=False)
    op.create_index(op.f('ix_al_snippet_annotation_model_checkpoint_id'), 'al_snippet_annotation', ['model_checkpoint_id'], unique=False)
    op.create_index(op.f('ix_al_snippet_annotation_snippet_id'), 'al_snippet_annotation', ['snippet_id'], unique=False)
    op.create_index(op.f('ix_al_snippet_annotation_user_id'), 'al_snippet_annotation', ['user_id'], unique=False)
    op.create_table('al_vis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('model_checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('snippet_id', sa.Integer(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('diversity', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('model_predicted_labels', sa.JSON(), nullable=True),
    sa.Column('model_predicted_probabilities', sa.JSON(), nullable=True),
    sa.Column('trusted_labels', sa.JSON(), nullable=True),
    sa.Column('latent_embedding', sa.JSON(), nullable=True),
    sa.Column('pca_2d_x', sa.Float(), nullable=True),
    sa.Column('pca_2d_y', sa.Float(), nullable=True),
    sa.Column('pca_3d_x', sa.Float(), nullable=True),
    sa.Column('pca_3d_y', sa.Float(), nullable=True),
    sa.Column('pca_3d_z', sa.Float(), nullable=True),
    sa.Column('umap_2d_x', sa.Float(), nullable=True),
    sa.Column('umap_2d_y', sa.Float(), nullable=True),
    sa.Column('umap_3d_x', sa.Float(), nullable=True),
    sa.Column('umap_3d_y', sa.Float(), nullable=True),
    sa.Column('umap_3d_z', sa.Float(), nullable=True),
    sa.Column('tsne_2d_x', sa.Float(), nullable=True),
    sa.Column('tsne_2d_y', sa.Float(), nullable=True),
    sa.Column('tsne_3d_x', sa.Float(), nullable=True),
    sa.Column('tsne_3d_y', sa.Float(), nullable=True),
    sa.Column('tsne_3d_z', sa.Float(), nullable=True),
    sa.Column('isomap_2d_x', sa.Float(), nullable=True),
    sa.Column('isomap_2d_y', sa.Float(), nullable=True),
    sa.Column('isomap_3d_x', sa.Float(), nullable=True),
    sa.Column('isomap_3d_y', sa.Float(), nullable=True),
    sa.Column('isomap_3d_z', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_checkpoint_id'], ['al_model_checkpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_checkpoint_id', 'snippet_id', name='uq_al_vis_checkpoint_snippet')
    )
    op.create_index(op.f('ix_al_vis_dataset_id'), 'al_vis', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_al_vis_id'), 'al_vis', ['id'], unique=False)
    op.create_index(op.f('ix_al_vis_model_checkpoint_id'), 'al_vis', ['model_checkpoint_id'], unique=False)
    op.create_index(op.f('ix_al_vis_snippet_id'), 'al_vis', ['snippet_id'], unique=False)
    op.create_table('al_feedback_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('ACCEPT', 'REJECT', 'MODIFY', name='al_feedback_action_enum'), nullable=False),
    sa.Column('modified_labels', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['al_predictions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_al_feedback_events_id'), 'al_feedback_events', ['id'], unique=False)
    op.create_index(op.f('ix_al_feedback_events_prediction_id'), 'al_feedback_events', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_al_feedback_events_user_id'), 'al_feedback_events', ['user_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_al_feedback_events_user_id'), table_name='al_feedback_events')
    op.drop_index(op.f('ix_al_feedback_events_prediction_id'), table_name='al_feedback_events')
    op.drop_index(op.f('ix_al_feedback_events_id'), table_name='al_feedback_events')
    op.drop_table('al_feedback_events')

    op.drop_index(op.f('ix_al_vis_snippet_id'), table_name='al_vis')
    op.drop_index(op.f('ix_al_vis_model_checkpoint_id'), table_name='al_vis')
    op.drop_index(op.f('ix_al_vis_id'), table_name='al_vis')
    op.drop_index(op.f('ix_al_vis_dataset_id'), table_name='al_vis')
    op.drop_table('al_vis')

    op.drop_index(op.f('ix_al_snippet_annotation_user_id'), table_name='al_snippet_annotation')
    op.drop_index(op.f('ix_al_snippet_annotation_snippet_id'), table_name='al_snippet_annotation')
    op.drop_index(op.f('ix_al_snippet_annotation_model_checkpoint_id'), table_name='al_snippet_annotation')
    op.drop_index(op.f('ix_al_snippet_annotation_label'), table_name='al_snippet_annotation')
    op.drop_index(op.f('ix_al_snippet_annotation_dataset_id'), table_name='al_snippet_annotation')
    op.drop_table('al_snippet_annotation')

    op.drop_index(op.f('ix_al_predictions_snippet_id'), table_name='al_predictions')
    op.drop_index(op.f('ix_al_predictions_model_checkpoint_id'), table_name='al_predictions')
    op.drop_index(op.f('ix_al_predictions_id'), table_name='al_predictions')
    op.drop_table('al_predictions')

    op.drop_index(op.f('ix_al_retrain_jobs_model_checkpoint_id'), table_name='al_retrain_jobs')
    op.drop_index(op.f('ix_al_retrain_jobs_id'), table_name='al_retrain_jobs')
    op.drop_index(op.f('ix_al_retrain_jobs_dataset_id'), table_name='al_retrain_jobs')
    op.drop_table('al_retrain_jobs')

    op.drop_index(op.f('ix_al_model_checkpoints_parent_checkpoint_id'), table_name='al_model_checkpoints')
    op.drop_index(op.f('ix_al_model_checkpoints_id'), table_name='al_model_checkpoints')
    op.drop_index(op.f('ix_al_model_checkpoints_dataset_id'), table_name='al_model_checkpoints')
    op.drop_table('al_model_checkpoints')
    # ### end Alembic commands ###

