
# app/core/al_defaults.py

from active_learning import config

DEFAULT_INFERENCE_THRESHOLD = config.DEFAULT_INFERENCE_THRESHOLD
DEFAULT_DENSITY_K = config.DEFAULT_DENSITY_K
DEFAULT_COMPOSITE_WU = config.DEFAULT_COMPOSITE_WU
DEFAULT_COMPOSITE_WD = config.DEFAULT_COMPOSITE_WD
DEFAULT_COMPOSITE_WR = config.DEFAULT_COMPOSITE_WR

retrain_after = config.RETRAIN_AFTER